### PR TITLE
Config2nd display

### PR DESCRIPTION
**Pull request by claudegel**

### CODE REVIEW

**Comment by chrisbklein** [comment]
Hello Claude - Chris here from Lac-Delage (QC)
I just installed a Sinope thermostat [TH1123ZB] using the Sonoff [USB Zigbee 3 pro].
Everything works fine except I don't understand how to get the outside temperature to display on the Sinope thermostat and I also don't see the actual state like heating - away - etc. on the thermostat display.
What do I need to do in terms of code changes?  

Chris

**Comment by claudegel** [comment]
Hi Chris,
to send temperature to your thermostat you need first to set a sensor that will get outside temperature from somewhere. Could be local temperature measured directly outside  with a sensor or get temperature form other weather component like openweathermap, dark sky, météo canada etc there are many on HA.
then you need to set an automation that will send temperature to your thermostat at least once per hour or your thermostat will go back to setpoint temperature. here is an example:
```
- alias: Send-OutdoorTemp
  trigger:
    - platform: state
      entity_id: sensor.local_temp # sensor to get local temperature
  variables:
    thermostats:
      - 50:0b:91:40:00:02:2d:6d  #ieee of your thermostat dvices, one per line
      - 50:0b:91:40:00:02:2a:65
  action:
    - repeat:  #service will be call for each ieee
        count: "{{thermostats|length}}"
        sequence:
          - service: zha.set_zigbee_cluster_attribute
            data:
              ieee: "{{ thermostats[repeat.index-1] }}"
              endpoint_id: 1
              cluster_id: 0xff01 # 65281
              cluster_type: in
              attribute: 0x0010 # 16
              value: "{{ ( trigger.to_state.state|float * 100 ) |int }}" # sending temperature in hundredth of a degree
            mode: single
```
For the sensor it could be reading temperature from other neviweb device or from other weather services:

```
template:
  - sensor:
      - name: "outdoor_temp"
        unit_of_measurement: '°C'
        device_class: temperature
        state_class: measurement
        state: "{{ state_attr('switch.neviweb130_switch_mc3100zb', 'Extern_temperature') }}"
      - name: "outside_temp"
        unit_of_measurement: '°C'
        device_class: temperature
        state_class: measurement
        state: "{{ state_attr('weather.dark_sky', 'temperature') }}"
```
For the display it depend on what type of lovelace thermostat card you pick.
If you check on my other custom_components for HA like sinope-130 you will see more example in the doc for the card setup and display

**Comment by claudegel** [comment]
Hi Chris
You can put everything in the file configuration.yaml but doing so you will end up with a very big file. So normally we splitt things is different file and refer to them in the configuration.yaml file

First for the configuration.yam, add those lines:
```
group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
timer: !include timer.yaml
template: !include template.yaml
```
Note: when you write code like what I did above highlight it with your mouse and click the <> above. This will keep the formating correctly.

Once you have those line added in configuration.yaml them you will need to create some files.
- In the config dir create a directory called: automation
- in the config directory, where you have the configuration.yaml create the following files
  - groups.yaml
  - scripts.yaml
  - scenes.yaml
  - sensor.yaml
  - timer.yaml
  - template.yaml
For now those files are empty.

In template.yaml you will put your sensor for outside temperature
```
  - sensor:
      - name: "outdoor_temp"
        unit_of_measurement: '°C'
        device_class: temperature
        state_class: measurement
        state: "{{ state_attr('switch.neviweb130_switch_mc3100zb', 'Extern_temperature') }}"
```
note that you don't need to write the word template. Also the first line - sensor have two spaces before.
Once you have selected your weather source let me know and I'll tell you what to write exactly in template.yaml

For the automation that send the outside temperature to the thermostat you will place it in the automation directory.
Create a file like auto_update.yaml. in that file you will place all the automations related to the update sent to your thermostats or other devices. For now just put this:
```
- alias: Send-OutdoorTemp
  trigger:
    - platform: state
      entity_id: sensor.outdoor_temp # sensor to get local temperature. the one you use in template.yaml
  variables:
    thermostats:
      - 50:0b:91:40:00:02:2d:6d  #ieee of your thermostat devices, one per line
      - 50:0b:91:40:00:02:2a:65
  action:
    - repeat:  #service will be call for each ieee
        count: "{{thermostats|length}}"
        sequence:
          - service: zha.set_zigbee_cluster_attribute
            data:
              ieee: "{{ thermostats[repeat.index-1] }}"
              endpoint_id: 1
              cluster_id: 0xff01 # 65281
              cluster_type: in
              attribute: 0x0010 # 16
              value: "{{ ( trigger.to_state.state|float * 100 ) |int }}" # sending temperature in hundredth of a degree
            mode: single
```
So first tell me what temperature data you want to use:
- Dark Sky
- Openweathermap
- Environnement Canada
- Local sensor outside of your house

**Comment by chrisbklein** [comment]
Thank you for helping me Claude.

I did order a ZigBee temperature and humidity sensor from Amazon and this sensor will be here on Wednesday.
I want to measure the actual temperature here on Lac-Delage and that in intervals of 15 minutes. (if possible)

Chris

**Comment by claudegel** [comment]
Can you send me more info about that temperature sensor ?
Normally you don't need an interval as the automation will send new data to thermostat as soon as there is a temperature change on the sensor.
I it is a zigbee temperature sensor then you probably won't need to create a sensor as the device will have his own sensor.
Once you get it I'll guide you on how to set it with the automation

**Comment by chrisbklein** [comment]
I will do that as soon it is here.

Thank you very much Claude.

Chris

**Comment by chrisbklein** [comment]
Hallo again Claude

I did receive my sensor and I prepared everything as you described below.

I do run the thermostat directly on a ZigBee stick from Sonoff and I do no not have the Sinope neviweb130 which you refer to in the sensor script below.
I do not know where I can find the ieee address of the thermostat but I am supposed to enter the address into the script – correct? One address per thermostat as you say.

The name of the sensor outside is: sensor.lumi_lumi_weather_temperature

***@***.***

Thank you again for your help.

Chris

**Comment by aomann** [comment]
Hello,

The ieee number can be found on the device page.

C53FBB1D-E79E-410D-851F-ECEAA32EE99E

**Comment by chrisbklein** [comment]
Thank you Claude

Found it.

Chris

**Comment by chrisbklein** [comment]
Hello Claude.

Here is the Thermostat I did get today.

It is a Aqara: Model WSDCGQ11LM
Temperature and hunidity sensor.

Chris

PS:          Did everything you wrote to me.
                As of now there is no external temperature on the sinope thermostat display.



***@***.***

**Comment by claudegel** [comment]
I'm not sure this sensor goes outside. I've sent an email to aqara support to find out.
But as your aqara sensor is a zigbee then you can view it in ZHA. If you are using ZHA to manage your zigbee devices then you can go in parameters/devices and services. Open the ZHA card where it list all connected zigbee devices. Find your temperature sensor and open it. Then you will find the temperature sensor name. Put it in the automation below:
```
- alias: Send-OutdoorTemp
  trigger:
    - platform: state
      entity_id: sensor.aqara xxx # your aqara temperature sensor name found in ZHA
  variables:
    thermostats:
      - 50:0b:91:40:00:02:2d:6d  #ieee of your thermostat dvices, one per line
      - 50:0b:91:40:00:02:2a:65
  action:
    - repeat:  #service will be call for each ieee
        count: "{{thermostats|length}}"
        sequence:
          - service: zha.set_zigbee_cluster_attribute
            data:
              ieee: "{{ thermostats[repeat.index-1] }}"
              endpoint_id: 1
              cluster_id: 0xff01 # 65281
              cluster_type: in
              attribute: 0x0010 # 16
              value: "{{ ( trigger.to_state.state|float * 100 ) |int }}" # sending temperature in hundredth of a degree
            mode: single
```

**Comment by claudegel** [comment]
Sorry but your aqara temperature sensor is not set to be used outside. Response from aqara
Hi Claude,

Thank you for contacting us.

Our Aqara products are not rated for outdoor use and should not be exposed to rain or vapor.
​
If you have any other questions or concerns feel free to contact us. 
​
Sincerely, 
Caleb 
Aqara Technical Support

**Comment by chrisbklein** [comment]
Thank you for your answer Claude.

That is what I already did.
You are of cause correct and this sensor is not waterproof or supposed to be outside.
It is however in a total safe position and far away from moisture etc. and I will exchange it ones I get all of that to work.

Befor I did send you the email I already followed what you advised me to do in the older email but I was not successful with the code below.

auto_update.yaml

- alias: Send-OutdoorTemp
  trigger:
    - platform: state
      entity_id: sensor.lumi_lumi_weather_temperature # sensor to get local temperature. the one you use in template.yaml
  variables:
    thermostats:
      - 00:15:8d:00:08:a6:cd:0b  #ieee of your thermostat devices, one per line

  action:
    - repeat:  #service will be call for each ieee
        count: "{{thermostats|length}}"
        sequence:
          - service: zha.set_zigbee_cluster_attribute
            data:
              ieee: "{{ thermostats[repeat.index-1] }}"
              endpoint_id: 1
              cluster_id: 0xff01 # 65281
              cluster_type: in
              attribute: 0x0010 # 16
              value: "{{ ( trigger.to_state.state|float * 100 ) |int }}" # sending temperature in hundredth of a degree
            mode: single

template.yaml

- sensor:
  - name: "outdoor_temp"
    unit_of_measurement: '°C'
    device_class: temperature
    state_class: measurement
    state: "{{ state_attr('sensor.lumi_lumi_weather_temperature', 'Extern_temperature') }}"

**Comment by aomann** [comment]
Hello,

Try the following using the GUI:

040572E2-82E4-489A-BA25-BB039C3F14C8
600A55B6-7F84-4DA2-8556-BD889006F736

Replace the ieee with one of your thermostat.

It should display -10 as the outdoor temperature.

Alex

**Comment by aomann** [comment]
The service is Zigbee Home Automation: Set zigbee cluster attribute

**Comment by claudegel** [comment]
if you go in dev-tools/states what is the state for your sensor.lumi_lumi_weather_temperature, the second column should be the outside temperature if your sensor is outside.
Then if it is OK for the sensor temperature value the automation is like this
```
- alias: Send-OutdoorTemp
  trigger:
    - platform: state
      entity_id: sensor.lumi_lumi_weather_temperature # sensor to get local temperature
  variables:
    thermostats:
      - 00:15:8d:00:08:a6:cd:0b    #ieee of your thermostat devices, one per line
  action:
    - repeat:  #service will be call for each ieee
        count: "{{thermostats|length}}"
        sequence:
          - service: zha.set_zigbee_cluster_attribute
            data:
              ieee: "{{ thermostats[repeat.index-1] }}"
              endpoint_id: 1
              cluster_id: 0xff01 # 65281
              cluster_type: in
              attribute: 0x0010 # 16
              value: "{{ ( trigger.to_state.state|float * 100 ) |int }}" # sending temperature in hundredth of a degree
            mode: single
```
Your file auto_update.yaml should be in the folder config/automation/
and you should have this line in configuration.yaml
`automation: !include_dir_merge_list automation/`

**Comment by chrisbklein** [comment]
Hello Claude

The sensor state is as follows.

***@***.***

Chris

**Comment by chrisbklein** [comment]
Hello Claude

If you have the time you could have a look with team viewer.

Chris

**Comment by claudegel** [comment]
How can I do team viewer

**Comment by claudegel** [comment]
You say
```
Hello Claude

The sensor state is as follows.
```
But I can'y see the state value

**Comment by chrisbklein** [comment]
Hello Claude

1 135 323 770
v5n3uusq

Chris

**Comment by darouss99** [comment]
@chrisbklein Not the best place to let your teamviewer ID and Password.  Now all the internet can access your computer. You should generate new ID/Password and not let it on the internet.  Good evening.

**Comment by chrisbklein** [comment]
Password changes every time

**Comment by chrisbklein** [comment]
Hello Claude

-11.1

Chris

***@***.***

**Comment by claudegel** [comment]
So your sensor is sending -11.1
you should put the name of your sensor  in the automation
 - platform: state

      entity_id: your sensor device name
For teamviewer I need to do some configuration as I'm not on windows. let me try to install it first

**Comment by chrisbklein** [comment]
Again
Thank you.

I am here and can see when you log in to my system.

Chris

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by claudegel** [comment]
I'm ready to connect. need the password

**Comment by claudegel** [comment]
look like password not working

**Comment by chrisbklein** [comment]
I did send you an new one to your ***@***.******@***.***> address

**Comment by claudegel** [comment]
how can I talk to you on teamviewer.
Look like your automation is not there
You need to have in dev-tool/states automation.send_outdoortemp

**Comment by claudegel** [comment]
Chris, look like your automation is ok. I was able to reproduce the same error on mine and it is because we start it manually. in that case the trigger value is not there so it give an error about trigger don't have a state value. But when the automation is trigered by the temperature change there is a value in the trigger. So I presume that your automation is ok now. 
What do you have for the second display ? the setpoint value ?

**Comment by chrisbklein** [comment]
Hello Claude

Right now this is what is on the display.

***@***.***

Chris

**Comment by chrisbklein** [comment]
I did send you another email to phyto.

Chris

**Comment by chrisbklein** [comment]
Here is what I found out when I did install the minimalistic dashboard which polled in all the entities by itself.

***@***.***

As you can see: The outdoor_temp is Unknown.

The reason for that is:

***@***.***

And the explanation behind this is:

***@***.***

Chris

**Comment by chrisbklein** [comment]
Hello Claude

Seams to be a problem of that sensor since other people report the exact same problem.

Having issues with zigbee being Unavailable, never reporting battery - Configuration / Zigbee - Home Assistant Community (home-assistant.io)<https://community.home-assistant.io/t/having-issues-with-zigbee-being-unavailable-never-reporting-battery/273420>

I will get another one.

Chris

**Comment by claudegel** [comment]
Sorry Ghris, I was out today. So if it is the sensor which cause problem we can switch to a weather service. I think that you have installed openweathermap so you have access to sensor.openweathermap_temperature
Then replace sensor.lumi_lumi_weather_temperature in your automation by sensor.openweathermap_temperature
and restart HA

**Comment by claudegel** [comment]
In my home I use a Sinopé MC3100ZB which connect my Sedna valve to my alarm system. This device have an input to connect a temperature sensor. I bought a AC1310-01 floor sensor that come with 15 feet of wire. I've placed the sensor outside and connect it to the MC3100ZB inside and I get the local temperature.

**Comment by chrisbklein** [comment]
Hello Claude.

I did install zigbee2mqtt.
I did pair all the devices from scratch.
I am now able to see the set temperature on the secondary display of the sinope.
The exterior aqura temperature sensor is now working as well.

I did change the entity_id to the new values.
“ entity_id: sensor.external_sensor_office_windows_humidity_pressure_temperature_temperature “
(I hope this is correct)

I do not know what to change for the service because right now it still says:
“ - service: zha.set_zigbee_cluster_attribute”

What do I have to change there or anywhere else for that matter.

Chris

**Comment by claudegel** [comment]
You can't use zha services if your thermostat and sensor are now in zigbee2mqtt
You need to use another automation like this one
```
- id: 'Auto_Publish_Outdoor_Temprature'
  alias: Auto_Publish_Outdoor_Temprature
  description: Automatically Publish the outdoor temperature to thermostats
  trigger:
  - entity_id: sensor.outdoor_temprature_sensor  <--- put your sensor name here
    platform: state
  condition: []
  action:
  - data:
      payload_template: '{{ states(''**sensor.outdoor_temprature_sensor**'') | float * 100 |int }}' <--- put your sensor name here
      topic: zigbee2mqtt/<**FRIENDLY_NAME**>/set/thermostat_outdoor_temperature <--- name of your thermostat
    service: mqtt.publish
```
your sensor name is sensor.external_sensor_office_windows_humidity_pressure_temperature_temperature
You need to find the name of your thermostat

**Pull request merged**
